name: Developer Portal CI/CD
on: push
env: 
  KONG_KONNECT_TOKEN: ${{ secrets.KONG_KONNECT_TOKEN }}
  KONG_CP_NAME: rb-demo
  SERVICE_NAME: reqres
  TAG_NAME: api-demo
  PRODUCT_NAME: product-demo1
  

jobs:
  deploy-my-product:
    runs-on: ubuntu-latest
    steps:
    # - name: Setup deck
    #   uses: kong/setup-deck@v1
    #   with: 
    #     deck-version: 1.29.2
    - name: Clone repo
      uses: actions/checkout@v2
    # API Product Creation
      # We will check if API Product already exists by getting list of API Products filtered by name. 
      # If total value in the .meta.page.total is 0, that means no API Product with that name is present and we create a new API product else we will just get PRODUCT_ID to save it for further use.
    - name: create api product
      run: | 
        GET_API_PRODUCT_URL=https://us.api.konghq.com/v2/api-products/?filter%5Bname%5D=$PRODUCT_NAME
        echo $GET_API_PRODUCT_URL 
        echo $KONG_KONNECT_TOKEN
        echo $PRODUCT_NAME
        mkdir -p results
        curl --request GET --url $GET_API_PRODUCT_URL --header "Authorization:Bearer $KONG_KONNECT_TOKEN" > results/apiProducts.json
        total=$(cat results/apiProducts.json | jq ".meta.page.total")
        echo $total
        POST_CREATE_API_PRODUCT_URL=https://us.api.konghq.com/v2/api-products
        echo "Creating API Product............"
        PRODUCT_ID=$(
            if [ "$total" -eq "0" ]; then
                curl --request POST $POST_CREATE_API_PRODUCT_URL  \
                --header "Authorization:Bearer $KONG_KONNECT_TOKEN" \
                --header Content-Type:application/json \
                --data {\"name\":\"$PRODUCT_NAME\"} | jq -r ".id"; else cat results/apiProducts.json | jq -r '.data[0].id';
            fi
            )
        echo "PRODUCT ID is ....: " $PRODUCT_ID
     